# Bundle workflow
# Contains:
# + php-cs-fixer fix
# + rector process
name: Bundle

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  code-quality-automation:
    name: Automated code quality, updates and fixes
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Prep'
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      -
        name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      -
        name: 'Composer'
        run: |
          composer config --no-plugins allow-plugins.composer/installers true
          composer config --no-plugins allow-plugins.silverstripe/recipe-plugin true
          composer config --no-plugins allow-plugins.silverstripe/vendor-plugin true
          composer config --no-plugins allow-plugins.phpstan/extension-installer true
          composer install --ansi --no-interaction --no-progress

      -
        name: 'PHP-CS-Fixer (fix)'
        # run unless the branch contains this label
        if: ${{ !contains(github.ref_name, 'no-cs-fix') }}
        # config uses base of caller module
        run: vendor/bin/php-cs-fixer fix --ansi --no-interaction --show-progress=none --config vendor/nswdpc/ci-files/php-cs-fixer/.php-cs-fixer.php

      -
        # commit only to core contributors who have repository access
        name: 'PHP-CS-Fixer (commit)'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[php-cs-fixer] Automated updates generated by php-cs-fixer configuration'

      -
        name: 'Rector (process)'
        # run unless the branch contains this label
        if: ${{ !contains(github.ref_name, 'no-rector') }}
        # config uses base of caller module
        run: vendor/bin/rector process --no-diffs --ansi --config vendor/nswdpc/ci-files/rector/.rector.silverstripe.php

      -
        # commit only to core contributors who have repository access
        name: 'Rector (commit)'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[rector] Automated updates generated by rector configuration'

      -
        name: 'PHPStan (analyse)'
        continue-on-error: true
        # run unless the branch contains this label
        if: ${{ !contains(github.ref_name, 'no-phpstan') }}
        # config uses base of caller module
        run: vendor/bin/phpstan analyse --ansi --no-progress --no-interaction --configuration vendor/nswdpc/ci-files/phpstan/phpstan.neon.dist --error-format github
