# github action that fixes code based on configuration
name: php-cs-fixer

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  php-cs-fixer:
    if: ${{ github.event_name == 'push' || endsWith(github.ref_name, "-cs-fix") }}
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Prep'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      -
        name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      -
        name: 'Composer'
        run: |
          composer config --no-plugins allow-plugins.composer/installers true
          composer config --no-plugins allow-plugins.silverstripe/recipe-plugin true
          composer config --no-plugins allow-plugins.silverstripe/vendor-plugin true
          composer config --no-plugins allow-plugins.phpstan/extension-installer true
          composer install --ansi --no-interaction --no-progress

      -
        name: 'PHP-CS-Fixer (fix)'
        # config uses base of caller module
        run: vendor/bin/php-cs-fixer fix --ansi --no-interaction --config vendor/nswdpc/ci-files/php-cs-fixer/.php-cs-fixer.php

      -
        # commit only to core contributors who have repository access
        name: 'Commit action'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[php-cs-fixer] Automated updates generated by php-cs-fixer configuration'
          commit_author: 'GitHub Action <actions@github.com>'
          commit_user_email: 'action@github.com'
