# PHPCSFixer workflow
# + PHP 8.3
# + Silverstripe
# Contains:
# + php-cs-fixer fix
name: php-cs-fixer silverstripe

on:
  workflow_call: null

jobs:
  bundle:
    uses: ./.github/workflows/_silverstripe_phpcsfixer.yml
    with:
      php-version: '8.3'
