# PHPStan workflow
# + PHP 8.5
# + Silverstripe
# Contains:
# + phpstan analyse
# Requires
# + suggested Silverstripe phpstan module to be installed in project (see composer.json)
name: phpstan silverstripe

on:
  workflow_call: null

jobs:
  bundle:
    uses: ./.github/workflows/_silverstripe_phpstan.yml
    with:
      phpstan-config: .phpstan.silverstripe.neon
      php-version: '8.5'
