# PHPStan targeting only php 8.3
name: phpstan silverstripe

on:
  workflow_call: null

jobs:
  bundle:
    uses: ./.github/workflows/_silverstripe_phpstan.yml
    with:
      phpstan-config: .phpstan.silverstripe.neon
      php-versions: '["8.3"]'
