# PHPStan workflow retained for BC, see phpstan.silverstripe.yml
name: phpstan silverstripe

on:
  workflow_call: null

jobs:
  bundle:
    uses: ./.github/workflows/_silverstripe_phpstan.yml
    with:
      phpstan-config: .phpstan.silverstripe.neon
