# Rector workflow
# + PHP 8.5
# + Silverstripe 6
# + Rector phpset: php83
# Contains:
# + rector process
# Requires
# + suggested Silverstripe rector module to be installed in project (see composer.json)
name: rector silverstripe

on:
  workflow_call: null

jobs:
  bundle:
    uses: ./.github/workflows/_silverstripe_rector.yml
    with:
      rector-config: .rector.silverstripe_6_83.php
      php-version: '8.5'
