# Rector workflow
# + PHP 8.3
# + Silverstripe
# + Rector phpset: php83
# Contains:
# + rector process
# Requires
# + suggested Silverstripe rector module to be installed in project (see composer.json)
name: rector silverstripe

on:
  workflow_call: null

jobs:
  bundle:
    uses: ./.github/workflows/_silverstripe_rector.yml
    with:
      rector-config: .rector.silverstripe.php
      php-version: '8.3'
