# github action that checks code with Rector
# requires suggested silverstripe rector module (see composer.json)
name: rector silverstripe

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  rector:
    name: 'rector'
    if: ${{ github.event_name == 'pull_request' && !contains(github.ref_name, 'no-rector') }}
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Prep'
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v4
        with:
          # Must be used to trigger workflow after push
          token: ${{ secrets.ACCESS_TOKEN }}

      -
        name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      -
        name: 'Composer'
        run: |
          composer config --no-plugins allow-plugins.composer/installers true
          composer config --no-plugins allow-plugins.silverstripe/recipe-plugin true
          composer config --no-plugins allow-plugins.silverstripe/vendor-plugin true
          composer config --no-plugins allow-plugins.phpstan/extension-installer true
          composer install --ansi --no-interaction --no-progress

      -
        name: 'Rector (process)'
        # config uses base of caller module
        run: vendor/bin/rector process --no-diffs --ansi --config vendor/nswdpc/ci-files/rector/.rector.silverstripe_5_83.php

      -
        # commit only to core contributors who have repository access
        name: 'Rector (commit)'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[rector] Automated updates generated by rector silverstripe configuration'
