# Bundle workflow
# + PHP 8.3
# + Silverstripe 5
# + Rector phpset: php81
# Contains:
# + rector process
# + php-cs-fixer fix
# Requires
# + suggested Silverstripe rector module to be installed in project (see composer.json)
name: Bundle

on:
  workflow_call: null

jobs:
  bundle:
    uses: ./.github/workflows/_silverstripe_bundle.yml
    with:
      rector-config: .rector.silverstripe_5_81.php
      php-version: '8.3'
